# Generated by Django 5.1.4 on 2024-12-15 17:40

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(default='static/img/imag_1.jpg', upload_to='uploads')),
                ('title', models.CharField(default='notitle', max_length=200)),
                ('author_name', models.CharField(default='anonymous', max_length=50)),
                ('aurthor_photo', models.ImageField(blank=True, default='static/img/imag_1.jpg', null=True, upload_to='author')),
                ('date', models.DateField(default='timezone')),
                ('content', models.TextField(default='no content to see')),
                ('content_img', models.ImageField(default='there is no content', upload_to='content_img')),
                ('Categorie', models.ForeignKey(default='none', on_delete=django.db.models.deletion.PROTECT, to='bw.categories')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
