# Generated by Django 5.1.4 on 2024-12-15 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.TextField(default='pls be nice')),
                ('post_comment', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bw.post_data')),
            ],
        ),
    ]
