# Generated by Django 5.1.4 on 2024-12-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
