# Generated by Django 5.1.4 on 2024-12-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bw', '0002_comment_blog_id_alter_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog_id',
        ),
    ]
