# Generated by Django 5.1.4 on 2024-12-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bw', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_comment',
        ),
    ]
