# Generated by Django 5.1.4 on 2024-12-15 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bw', '0003_remove_comment_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_comment',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bw.post_data'),
        ),
    ]
