# Generated by Django 5.1.4 on 2024-12-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bw', '0003_remove_comment_blog_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='body',
        ),
    ]
