# Generated by Django 5.1.4 on 2024-12-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bw', '0004_rename_comment_content_comment_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='annonymus', max_length=50)),
                ('phone', models.CharField(default='01000000000', max_length=11)),
                ('email', models.EmailField(default='a@gmail.con', max_length=254)),
                ('body', models.TextField(default='pls be nice')),
            ],
        ),
    ]
